import type { Metadata } from "next";
import { Roboto, Ms_Madi } from "next/font/google";
import "./globals.css";

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["vietnamese"],
});

const msMadiFont = Ms_Madi({
  variable: "--font-ms-madi",
  subsets: ["vietnamese"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "VTravel - Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFont.variable} ${msMadiFont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
