import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/app/layouts/header";
import Footer from "@/app/layouts/footer";

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "VTravel - Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${robotoFont.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
